// const myprogram=['js', 'c', 'python', 'c++'];
// console.log("my fav prog lang is " + myprogram);
// console.log(`my fav prog lang is  ${myprogram}`);
// let[top1,top2,top3,top4]=myprogram;
// console.log( `my fav prog is   ${top1}`);
// console.log(myprogram.length);
// let [top1,,,toplast]=myprogram;
// console.log(`my fv prog lag is ${toplast}`);
let top1, top2;
[top1, top2] = myprogram;
console.log(`my fav prog lamg is ${top2} `);